# Generated by Django 3.2 on 2022-07-19 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firm_name', models.CharField(default='大白小黑机器人', max_length=30)),
                ('license_plate', models.CharField(blank=True, default='桂A6666', max_length=30)),
                ('driver_name', models.CharField(blank=True, default='张三', max_length=10)),
                ('driver_gender', models.CharField(blank=True, default='', max_length=2)),
                ('idcard_number', models.CharField(blank=True, default='', max_length=30)),
                ('phone_number', models.CharField(blank=True, default='', max_length=30)),
                ('pre_deposit_amount', models.IntegerField(blank=True, default=0)),
            ],
        ),
    ]
