# Generated by Django 3.2 on 2022-07-19 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='id',
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='firm_name',
            field=models.CharField(default='大白小黑机器人', max_length=30, primary_key=True, serialize=False),
        ),
    ]
