# Generated by Django 3.2 on 2022-08-16 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_auto_20220720_0213'),
    ]

    operations = [
        migrations.CreateModel(
            name='SandInfo',
            fields=[
                ('sand_class', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('sand_price', models.IntegerField(blank=True, default=1)),
            ],
        ),
    ]
